[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
protocol = { path = "../protocol" }
anyhow.workspace = true
dotenvy.workspace = true
clap.workspace = true
