[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
anyhow.workspace = true
dotenvy.workspace = true
chrono = "0.4.39"
serde_json.workspace = true
